### ISSUE TITLE
TypeError in tangent.grad for array method.

### ISSUE THREAD

**Issue by jkitchin** [google/tangent#34] opened 2017-11-09 20:58 UTC
This may be related to issue #18 
```
def f(x):
    return x.sum()

df = tangent.grad(f)
```

but it raises a different kind of error:

```
TypeError: unhashable type: 'numpy.ndarray'
```

This works fine:

```
def f(x):
    return np.sum(x)

df = tangent.grad(f)
print df(np.array([1, 2, 3]))
```

#+RESULTS:
:RESULTS:
[1 1 1]

**Comment by mdanatg** [comment] 2017-11-09 21:06
Duplicate of #18

**Closed by mdanatg** 2017-11-09 21:06 UTC
