### ISSUE TITLE
functions which are partially constant cannot be differenciated.

### ISSUE THREAD

**Issue by xwhisky** [google/tangent#79] opened 2018-06-05 23:01 UTC
def f(x):
        if x < 0:
                a = 0
        else:
                a = x
        return a

cannot be differenciated, but 

def f(x):
        if x < 0:
                a = x - x 
        else:
                a = x
        return a

works just fine.

**Comment by bartvm** [comment] 2018-08-08 19:20
This is a duplicate of #82 I believe, should be fixed now, sorry for the slow response!

**Closed by bartvm** 2018-08-08 19:20 UTC
